// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwniuibwpdecgntmrhsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bml1aWJ3cGRlY2dudG1yaHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDgyNDEsImV4cCI6MjA3MTEyNDI0MX0.jKjlq3hmC7a9P7CthfWiw79a0q2YghXQLeEyOUwu_d4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});